version: "3.9"
services:
  proxy:
    image: node:20-alpine
    working_dir: /app
    environment:
      - NODE_ENV=development
      - PORT=4000
      - ALLOW_HOSTS=gibs.earthdata.nasa.gov,opengeo.ncep.noaa.gov,nomads.ncep.noaa.gov
    ports: ["4000:4000"]
    volumes:
      - ./services/proxy:/app
    command: sh -c "npm i && npm run dev"
  web:
    working_dir: /app
    image: node:20-alpine
    command: sh -c "npm i && npm run dev"
    ports: ["5173:5173"]
    volumes:
      - ./web:/app
