import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { createRoot } from 'react-dom/client';
import App from './ui/App';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { MantineProvider } from '@mantine/core';
import { ModalsProvider } from '@mantine/modals';
import { Notifications } from '@mantine/notifications';
import '@mantine/core/styles.css';
import '@mantine/charts/styles.css';
import '@mantine/notifications/styles.css';
import '@mantine/dates/styles.css';
import { vortexaTheme } from './theme';
const qc = new QueryClient();
createRoot(document.getElementById('root')).render(_jsx(MantineProvider, { theme: vortexaTheme, children: _jsxs(ModalsProvider, { children: [_jsx(Notifications, { position: "top-right" }), _jsx(QueryClientProvider, { client: qc, children: _jsx(App, {}) })] }) }));
