name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm run validate:catalog
      - run: pnpm run validate:inventory
      - run: pnpm -w run test
  infra-validate:
    runs-on: ubuntu-latest
    if: ${{ always() && hashFiles('infra/terraform/**') != '' }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5
      - name: Validate terraform
        working-directory: infra/terraform
        run: |
          terraform init -backend=false
          terraform validate
