name: CI
on:
  push:
    branches:
      - '**' # run on all branches so feature/fix branches are validated
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  history:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 50
      - name: Verify history coverage
        run: node scripts/verify-history-coverage.js
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Validate catalog
        run: pnpm run validate:catalog
      - name: Validate inventory
        run: pnpm run validate:inventory
      - name: Format check
        run: pnpm run format:check || (echo 'Run pnpm format locally' && exit 1)
      - name: Type check (build)
        run: pnpm run typecheck
      - name: Test
        run: pnpm -w run test
  infra-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5
      - name: Terraform format & validate
        working-directory: infra/terraform
        run: |
          terraform fmt -check
          terraform init -backend=false
          terraform validate
